config/routes.rb
Rails.application.routes.draw do

  resources :bills
  devise_for :lawmakers

  root 'bills#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
end

app/models/lawmaker.rb
class Lawmaker < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:title, :end_date, :description, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= simple_form_for(@bill) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :end_date %>
    <%= f.input :description %>
    <%= f.input :author %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bills/_nav.html.erb
<nav class="navbar-custom">


    <div id="nav-title" class="col-xs-6 col-sm-2">
      &nbsp;&nbsp;&nbsp;CitizenApp
    </div>

</nav>
<br>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
  <div class="container-show">

      <% @bills.each do |bill| %>
      <div class="col-xs-6 col-sm-5 col-md-4 col-lg-3">
          <a href="<%= bill_path(bill)%>">
            <div class="bill-image-link">
              <div class="bill-title"><%= bill.title %></div>
            </div>
          </a>
      </div>
        <% end %>
  </div>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>



    <div class="bill-title-show-container">
      <div class="bill-title-show">

      <h4><%= @bill.title %></h4><br>
      <strong>Description:</strong>
      <p><%= @bill.description %></p><br>
      <strong>End date:</strong>
      <p><%= @bill.end_date %></p><br>
      <strong>Author:</strong>
      <p><%= @bill.author %></p>
      </div>
    </div>

    <div class="edit-buttons" >
      <div class="btn btn-group">
        <%= link_to "Edit", edit_bill_path(@bill) %>
        <%= link_to "Delete", bill_path(@bill), method: :delete, data: {confirm: "Confirm Deletion?"} %>
        <%= link_to "Back", bills_path %>
      </div>
    </div>


      </div>

    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CitizenApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= render 'nav' %>



  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</nav>
<%= yield %>

</body>
</html>